name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'  # Trigger on changes within the "src" directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step to set up JDK (required to run Gradle)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' # Update to match your project's Java version

      # Step to grant execution permissions to the Gradle wrapper
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Step to run Gradle build
      - name: Run Gradle build
        run: ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        run: |
          docker build . --file Dockerfile --tag facuerro/pampagrow:latest
          docker push facuerro/pampagrow:latest